manifest:
  version: "0.13"
  remotes:
    - name: zephyrproject
      url-base: https://github.com/kunoh
  defaults:
    remote: zephyrproject

  projects:
    - name: zephyr
      repo-path: zephyr
      path: zephyr
      revision: user_allocation_off_ramdisk_buffer
      import:
        path-prefix: zephyrproject
  self:
    path: mcu-project
