manifest:
  version: "0.12"
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
  defaults:
    remote: zephyrproject

  projects:
    - name: zephyr
      repo-path: zephyr
      path: zephyr
      revision: v3.1.0
      import:
        path-prefix: zephyrproject
  self:
    path: mcu-project
